export interface Member {
  id: string
  name: string
  initials: string
  avatar?: string
  phone: string
  email: string
  status: "Guest" | "Member" | "Leader"
  fellowship: string
  department?: string
  memberType: "adult" | "child"
  activityStatus: "active" | "inactive"
  joinedAt: string
}

export const mockMembers: Member[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    initials: "SJ",
    phone: "(555) 123-4567",
    email: "sarah.j@citymega.org",
    status: "Leader",
    fellowship: "Kawangware Fellowship",
    department: "Choir",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-05-10",
  },
  {
    id: "2",
    name: "David Chen",
    initials: "DC",
    phone: "(555) 987-6543",
    email: "d.chen@citymega.org",
    status: "Member",
    fellowship: "Roysambu Fellowship",
    department: "Media",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-05-18",
  },
  {
    id: "3",
    name: "Miriam Wallace",
    initials: "MW",
    phone: "(555) 444-2211",
    email: "m.wallace@citymega.org",
    status: "Guest",
    fellowship: "None",
    memberType: "adult",
    activityStatus: "inactive",
    joinedAt: "2026-04-02",
  },
  {
    id: "4",
    name: "Arthur Manning",
    initials: "AM",
    phone: "(555) 667-8899",
    email: "arthur.m@citymega.org",
    status: "Member",
    fellowship: "Ng'ando Fellowship",
    department: "Ushers",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-03-15",
  },
  {
    id: "5",
    name: "Chloe Richards",
    initials: "CR",
    phone: "(555) 234-5678",
    email: "chloe@citymega.org",
    status: "Leader",
    fellowship: "Kawangware Fellowship",
    department: "Youth",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-05-19",
  },
  {
    id: "6",
    name: "Emmanuel Okonkwo",
    initials: "EO",
    phone: "(555) 345-6789",
    email: "e.okonkwo@citymega.org",
    status: "Member",
    fellowship: "Utawala Fellowship",
    department: "Welfare",
    memberType: "adult",
    activityStatus: "inactive",
    joinedAt: "2026-01-20",
  },
  {
    id: "7",
    name: "Grace Williams",
    initials: "GW",
    phone: "(555) 456-7890",
    email: "grace.w@citymega.org",
    status: "Member",
    fellowship: "Roysambu Fellowship",
    department: "Children",
    memberType: "child",
    activityStatus: "active",
    joinedAt: "2026-05-12",
  },
  {
    id: "8",
    name: "James Okoro Jr.",
    initials: "JO",
    phone: "(555) 567-8901",
    email: "j.okoro@citymega.org",
    status: "Member",
    fellowship: "Kawangware Fellowship",
    department: "Ushers",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-02-08",
  },
  {
    id: "9",
    name: "Faith Njeri",
    initials: "FN",
    phone: "(555) 678-9012",
    email: "f.njeri@citymega.org",
    status: "Leader",
    fellowship: "Kasarani Fellowship",
    department: "Choir",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-04-20",
  },
  {
    id: "10",
    name: "Peter Obi",
    initials: "PO",
    phone: "(555) 789-0123",
    email: "p.obi@citymega.org",
    status: "Member",
    fellowship: "Ng'ando Fellowship",
    department: "Media",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-03-01",
  },
  {
    id: "11",
    name: "Ruth Eze",
    initials: "RE",
    phone: "(555) 890-1234",
    email: "r.eze@citymega.org",
    status: "Leader",
    fellowship: "Ngong Fellowship",
    department: "Welfare",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-01-15",
  },
  {
    id: "12",
    name: "Daniel Ochieng",
    initials: "DO",
    phone: "(555) 901-2345",
    email: "d.ochieng@citymega.org",
    status: "Member",
    fellowship: "Embakasi Fellowship",
    department: "Youth",
    memberType: "adult",
    activityStatus: "active",
    joinedAt: "2026-05-05",
  },
]

export function getMembersByFellowship(fellowshipName: string): Member[] {
  return mockMembers.filter((member) => member.fellowship === fellowshipName)
}
